//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Müşteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Müşteriler()
        {
            this.Satış = new HashSet<Satış>();
        }
    
        public int Musteriid { get; set; }
        [Required(ErrorMessage = "Müşteri Adını Giriniz!!!")]
        [StringLength(50,ErrorMessage ="En fazla 50 Karakterlik İsim girin")]
        public string MusteriAd { get; set; }
        public string MusteriSoyAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satış> Satış { get; set; }
    }
}
